doc: update getting started
opea-project/docs pull request #100
Opened 2024-09-10 00:25 UTC by dbkinder

Work-in-progress to update the getting started information.

2024-09-10 00:26 UTC, dbkinder commented
@tomlenth @craigmateo Here's the word-to-rst conversion to get us started on an updated getting started guide.  (It needs some work, so let's talk)

2024-09-10 17:36 UTC, mkbhanda requested changes

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +   a. Basic deployment options suitable for proof of concept includes single architectures such as:
Make this a more general statement.
Basic deployment options suitable for proof of concept includes a single node, which is either a virtual machine, physical server, which could be local or in a Cloud Service Provider (CSP) environment or an AI PC with adequate memory that has a single container engine such as Docker or Podman. (by nature of the node description .. single architecture?). We have tested thus far on Intel Xeons servers that are X86-based, Intel Gaudi2, and Nvidia H100.  (if itemizing, treat all equal)

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +      * An AI enable PC.
s/enable/enabled

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +      * Onprem or cloud based environments (including environments with NVIDIA GPUs).
s/based environments /based cluster environments running Kubernetes as the orchestrator.

Production environments are typically multi-node to handle scale and resiliency.
We have only tested Kubernetes environments, the flavor of Kubernetes does not matter. Currently at version 1.30

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +Do you have ideas and skills to build out genAI components, microservices, and
s/compoents, microservices/component microservices

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +solutions? Want to be part of these  early stages of this evolving technology?
s/solutions? Want to be part of these early stages of this evolving technology?/
solutions, their evaluation, or support? Want to be part of this evolving technology in its early stages?

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +Register for our mailing list:
s/Register for our mailing list:/Register to join our mailing list:

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +Subscribe to working group mailing lists
s/Subscribe to working group mailing lists/Subscribe to one or more of the working group mailing lists based on your interest:

2024-09-10 17:36 UTC, mkbhanda commented on getting-started/index.rst
> +Want to Go Deeper?
is this more to become a partner? With logo/quote etc?

2024-09-10 23:15 UTC, tomlenth reviewed
This all looks good.  The one thing we need to think about is a way to place the generic "Get Started" aimed at developers who will consume these projects and "Like what you see" section that is aimed at contributors.  I initially envisioned a two column approach, but there's too much material for that.  Tabs may not work since there are headings in the body content of the tabbed material.  The main thing is that we don't want to have the contribution section buried below the fold.  Perhaps we need two "buttony" options at the top of the page that vectors viewers into "Try AI Solution" and "Contribute AI Solutions".

2024-09-11 00:55 UTC, yinghu5 approved these changes
LGTM

2024-09-11 00:57 UTC, mkbhanda requested changes

2024-09-11 03:31 UTC, dbkinder commented on getting-started/index.rst
> +      * A virtual machine or physical server, which could be local or in a Cloud
Could you provide what wording you'd like to see here instead?

2024-09-11 03:31 UTC, dbkinder commented on getting-started/index.rst
> +3. **Customize the chatbot with your own data (RAG model)**.
Here too. Could you provide the wording you'd like to see.

2024-09-11 21:53 UTC, mkbhanda commented
@dbkinder, I wonder if we can write the Getting Started as a story, reconciling with the different personas who may engage.

There are essentially four steps to getting started with OPEA, of which steps 3 and 4 are optional. 
1) Determine where you want to run your first GenAI application
2) Which of the OPEA samples you want to run
3) (optional) Whether and how you want to customize the OPEA sample application
4) (optional) Whether you want to evaluate the GenAI sample for accuracy, hallucinations, safety, bias etc. 

For the purposes of getting started, let us focus on a common use case: a ChatBot, which is covered by the ChatQnA sample. Further let us assume, as an end user you want to just create a proof of concept solution, no customizations of evaluation. 

Getting-Started ChatQnA Proof-of-Concept Simple
1) Determine where you want to run your first GenAI application - "Single Node".
   The single node could be an AI PC, a server, or a virtual machine, as long as it has adequate memory.  Single node deployments are most easily supported using a docker file approach.
2) Which of the OPEA samples you want to run - ChatQnA (ChatBot common use case). The simplest of single nodes that are widely available are X-86 architecture based. This translates to using docket-compose-chat_QnA_on_Intel_Xeon.  -- Takes the to the read me.


Getting-Started ChatQnA production
For scalability and resiliency people use a cluster of machines and launch and monitor their workloads on the cluster using an Orchestrator such as Kubernetes. Towards production readiness, run your application on a Kubernetes cluster. Further, for performance, one may want to use accelerators in one's cluster like Intel Gaudi, Nvidia GPUs etc. We currently have images for our samples that are specific to Intel CPU, called Xeons, and Intel Accelerator Gaudi. To keep things simple we assume you  have a Kubernetes cluster of Intel Xeons which is readily available on most Cloud Service Providers (CSPs) (EKS, AKS, GKE) or on-prem. Running large machine learning models on accelerators gives higher performance.
How to setup a Kubernetes cluster (on  EKS, AKS, GKE link or on-prem using KubeSpray/KubeAdm/..)
Provide link to ChatQnA helm chart link.

Getting-Started ChatQnA production and enterprise ready.
In a production environment with potentially multiple GenAI applications, there is opportunity to share common services and save on resources and thus cost. The OPEA GenAI Microservices Connector  provides, in addition to service sharing, additional features such as changing a model dynamically, defining GenAI pipelines with sequential, parallel and conditional steps.
<link to readme to GMC> followed by <Link to ChatQnA with GMC on Xeons>

OPEA solutions, homing in on the "Enterprise" in Open Platform for Enterprise AI, supports integration with enterprise functionalities such as Authentication, Authorization, Logging, Tracing, Observability, Guardrails and more. Some of these we provide through Service Mesh solutions such as Istio.  <link to Authn N&Z>, <link to GuardRails/Gateway>.


While we have not covered steps 3 and 4, Customization and Evaluation, we hint at what is possible and available. 
**Customization**. The ChatQnA GMC example illustrates how one may change the model-id used in the embedder, retriever and LLM components in the pipeline. One might also customize a pipeline by changing aspects like the vector database being used, the chunking algorithm, introducing different or additional guardrails, and even the model serving framework.  The GenAIComps sub-project hosts currently supported options in each GenAI pipeline component category.

**Evaluation** We have some initial benchmarking scripts to test for performance and accuracy in GenAIEval.

2024-09-18 17:19 UTC, dbkinder commented
We're going to abandon this PR in favor of a new one in the works...

2024-09-24 00:49 UTC, dbkinder commented
Closed and updated in #171 instead.

2024-09-24 00:49 UTC, closed without merging