xeon documentation
opea-project/docs pull request #123
Opened 2024-09-13 16:09 UTC by srinarayan-srikanthan

xeon documentation aligning to the new template.

2024-09-13 21:27 UTC, dbkinder approved these changes
Looks OK

2024-09-13 21:30 UTC, dbkinder requested changes
On second thought, I think you intend for this content to replace what's in the xeon.md doc, right? It shouldn't be a new file then.

2024-09-16 17:14 UTC, dbkinder approved these changes
LTGM, again.  Thanks!

2024-09-16 17:22 UTC, tomlenth approved these changes

2024-09-16 17:23 UTC, dbkinder approved these changes

2024-09-16 17:23 UTC, merged