Add documentation for Grafana monitoring for ChatQnA microservices
opea-project/docs pull request #172
Opened 2024-09-23 21:48 UTC by ctao456

Initial writeup of grafana monitoring, subject to changes over time.

2024-09-24 02:51 UTC, dbkinder requested changes
All this content is a duplication of what's already in examples/ChatQnA/ChatQnA_Guide.rst.  Why are we creating a new doc in this PR with the same content?

2024-09-24 02:51 UTC, dbkinder commented on examples/ChatQnA/deploy/monitoring.md
> +### Set up the Prometheus server
You shouldn't skip from the H1 (title) to an H3 heading.  This should be an H2 heading (with two leading ##).

2024-09-24 02:51 UTC, dbkinder commented on examples/ChatQnA/deploy/monitoring.md
> +#### 1. Download Prometheus:
... and all these numbered titles should be one level up (### not ####).  Also all these headings shouldn't end with `:`

2024-09-24 02:51 UTC, dbkinder commented on examples/ChatQnA/deploy/monitoring.md
> +### Set up the Grafana dashboard
This should be back to an H2 (##)

2024-09-24 02:51 UTC, dbkinder commented on examples/ChatQnA/deploy/monitoring.md
> +#### 1. Download Grafana:
And all these should be H3 (###)

2024-09-24 05:21 UTC, mkbhanda commented
Oh no, sad about duplicate effort.
Should we put graphana Prometheus etc in a central place and refer to it via link everywhere
________________________________
From: David Kinder ***@***.***>
Sent: Monday, September 23, 2024 7:51:31 PM
To: opea-project/docs ***@***.***>
Cc: Bhandaru, Malini ***@***.***>; Review requested ***@***.***>
Subject: Re: [opea-project/docs] Add documentation for Grafana monitoring for ChatQnA microservices (PR #172)


@dbkinder requested changes on this pull request.

All this content is a duplication of what's already in examples/ChatQnA/ChatQnA_Guide.rst. Why are we creating a new doc in this PR with the same content?

________________________________

In examples/ChatQnA/deploy/monitoring.md<https://github.com/opea-project/docs/pull/172#discussion_r1772484753>:

> @@ -0,0 +1,133 @@
+
+# Monitoring ChatQnA deployment
+
+Now that you have deployed the ChatQnA example, let's talk about monitoring the performance of the microservices in the ChatQnA pipeline.
+
+Monitoring the performance of microservices is crucial for ensuring the smooth operation of the generative AI systems. By monitoring metrics such as latency and throughput, you can identify bottlenecks, detect anomalies, and optimize the performance of individual microservices. This allows us to proactively address any issues and ensure that the ChatQnA pipeline is running efficiently.
+
+This document will help you understand how to monitor in real time the latency, throughput, and other metrics of different microservices. You will use **Prometheus** and **Grafana**, both open-source toolkits, to collect metrics and visualize them in a dashboard.
+
+### Set up the Prometheus server


You shouldn't skip from the H1 (title) to an H3 heading. This should be an H2 heading (with two leading ##).

________________________________

In examples/ChatQnA/deploy/monitoring.md<https://github.com/opea-project/docs/pull/172#discussion_r1772485421>:

> +Monitoring the performance of microservices is crucial for ensuring the smooth operation of the generative AI systems. By monitoring metrics such as latency and throughput, you can identify bottlenecks, detect anomalies, and optimize the performance of individual microservices. This allows us to proactively address any issues and ensure that the ChatQnA pipeline is running efficiently.
+
+This document will help you understand how to monitor in real time the latency, throughput, and other metrics of different microservices. You will use **Prometheus** and **Grafana**, both open-source toolkits, to collect metrics and visualize them in a dashboard.
+
+### Set up the Prometheus server
+
+Prometheus is a tool used for recording real-time metrics and is specifically designed for monitoring microservices and alerting based on their metrics.
+
+The `/metrics` endpoint on the port running each microservice exposes the metrics in the Prometheus format. The Prometheus server scrapes these metrics and stores them in its time series database. For example, metrics for the Text Generation Interface (TGI) service are available at:
+```bash
+http://${host_ip}:9009/metrics
+```
+
+To set up the Prometheus server, follow these steps:
+
+#### 1. Download Prometheus:


... and all these numbered titles should be one level up (### not ####). Also all these headings shouldn't end with :

________________________________

In examples/ChatQnA/deploy/monitoring.md<https://github.com/opea-project/docs/pull/172#discussion_r1772485715>:

> +
+#### 4. Access the Prometheus UI
+Access the Prometheus UI at the following URL:
+```bash
+http://localhost:9090/targets?search=
+```
+>Note: Before starting Prometheus, ensure that no other processes are running on the designated port (default is 9090). Otherwise, Prometheus will not be able to scrape the metrics.
+
+On the Prometheus UI, you can see the status of the targets and the metrics that are being scraped. You can search for a metrics variable by typing it in the search bar.
+
+The TGI metrics can be accessed at:
+```bash
+http://${host_ip}:9009/metrics
+```
+
+### Set up the Grafana dashboard


This should be back to an H2 (##)

________________________________

In examples/ChatQnA/deploy/monitoring.md<https://github.com/opea-project/docs/pull/172#discussion_r1772485892>:

> +http://localhost:9090/targets?search=
+```
+>Note: Before starting Prometheus, ensure that no other processes are running on the designated port (default is 9090). Otherwise, Prometheus will not be able to scrape the metrics.
+
+On the Prometheus UI, you can see the status of the targets and the metrics that are being scraped. You can search for a metrics variable by typing it in the search bar.
+
+The TGI metrics can be accessed at:
+```bash
+http://${host_ip}:9009/metrics
+```
+
+### Set up the Grafana dashboard
+Grafana is a tool used for visualizing metrics and creating dashboards. It can be used to create custom dashboards that display the metrics collected by Prometheus.
+
+To set up the Grafana dashboard, follow these steps:
+#### 1. Download Grafana:


And all these should be H3 (###)

—
Reply to this email directly, view it on GitHub<https://github.com/opea-project/docs/pull/172#pullrequestreview-2323878536>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAUTXVLII2YBZ6I5QW4VZQDZYDHTHAVCNFSM6AAAAABOW6WP7OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMRTHA3TQNJTGY>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-09-24 06:47 UTC, ctao456 commented
> All this content is a duplication of what's already in examples/ChatQnA/ChatQnA_Guide.rst. Why are we creating a new doc in this PR with the same content?

Hi @dbkinder. I checked history of examples/ChatQnA/ChatQnA_Guide.rst, and found this [commit](https://github.com/opea-project/docs/commit/44ab3aa3f7d988bdec7bb14f3c3781da374404d2) by @tomlenth and @mkbhanda that already included this content. Indeed, this PR is probably not needed.

2024-09-24 06:49 UTC, ctao456 commented
> Oh no, sad about duplicate effort. Should we put graphana Prometheus etc in a central place and refer to it via link everywhere

@mkbhanda There was not too much duplicated effort. I drafted the writeup of this monitoring section, and it's already pushed to examples/ChatQnA/ChatQnA_Guide.rst. Submitting this PR didn't take me a long time.

2024-09-27 01:45 UTC, dbkinder commented
Should we close this PR since the content is already in examples/ChatQnA/ChatQnA_Guide.rst ?

2024-09-27 02:01 UTC, ctao456 commented
> Should we close this PR since the content is already in examples/ChatQnA/ChatQnA_Guide.rst ?

Yes, David. Let's close this PR. Thank you for the comments on headings.

2024-09-27 02:02 UTC, closed without merging