add link to getting started across chatqna, different hardware modes
opea-project/docs pull request #191
Opened 2024-09-30 17:22 UTC by devpramod

2024-10-01 16:17 UTC, dbkinder requested changes

2024-10-01 16:17 UTC, dbkinder commented on examples/ChatQnA/deploy/gaudi.md
> +[Getting Started](https://opea-project.github.io/latest/getting-started/README.html) section. If you do
This links to the latest (main) documentation.  To keep the link within the released documentation you should use relative links to the file name to link to the document when that doc is within the same repo.  So, in this case, use `[Getting Started](/getting_started/README.md)`.  If the file is in a another OPEA repo, link to the source file (.md or ,,rst) with an URL to that file in the github.com repo.  The Sphinx processing converts references to .md files to the generate HTML file.

2024-10-01 16:17 UTC, dbkinder commented on examples/ChatQnA/deploy/xeon.md
> +[Getting Started](https://opea-project.github.io/latest/getting-started/README.html) section.
ditto

2024-10-18 07:16 UTC, yinghu5 approved these changes
LGTM

2024-10-18 07:17 UTC, merged