Adding Azure instructions
opea-project/docs pull request #237
Opened 2024-11-01 18:40 UTC by srinarayan-srikanthan

Added a tab for Azure and condensed two tabs to one.

2024-11-01 18:46 UTC, mkbhanda commented
@srinarayan-srikanthan  is there a way to include some ignores in the hyperlink tests? In particular for links that have an access token that we naturally cannot include to pass the failed test?

2024-11-01 18:48 UTC, srinarayan-srikanthan commented
@mkbhanda , yes looking into the fix for that.

2024-11-01 18:50 UTC, mkbhanda commented
Further, that Azure home page is very generic .. taking the user through a lot of questions .. unless of course that is the only way.

2024-11-01 19:18 UTC, mkbhanda requested changes
Let us be consistent, either use bold or double quotes of single quotes for commands/buttons/selection options. We currently have a mix.

2024-11-04 03:49 UTC, srinarayan-srikanthan commented on getting-started/README.md
> +10. Click Go to resource -> Connect -> Connect -> SSH using Azure CLI. Accept the terms and then select "Configure + connect"
yes

2024-11-04 07:22 UTC, chensuyue commented on getting-started/README.md
> +1. Navigate to [Microsoft Azure](portal.azure.com) – Select the "Skip" button on the bottom right to land on the service offerings page. Search for "Virtual Machines" in the search bar and select it.
Please use `https://portal.azure.com` instead of `portal.azure.com`.

2024-11-04 07:54 UTC, chensuyue commented
We will handle this issue in CI.

2024-11-04 19:13 UTC, srinarayan-srikanthan reviewed
done with all changes @mkbhanda

2024-11-04 19:18 UTC, tomlenth approved these changes

2024-11-04 19:23 UTC, preethivenkatesh approved these changes

2024-11-04 19:30 UTC, mkbhanda requested changes
2 minor edits suggested.

2024-11-04 19:30 UTC, mkbhanda commented on getting-started/README.md
> +> **Note:**  We recommend selecting a `c3-standard-22` or larger instance with an Intel(R) 4th Gen Xeon(C) Scalable Processor, and the minimum supported c3 instance type is c3-standard-8 with 32GB me
```suggestion
> **Note:**  We recommend selecting a `c3-standard-22` or larger instance with an Intel(R) 4th Gen Xeon(C) Scalable Processor, and the minimum supported c3 instance type is c3-standard-8 with 32GB memory. For more information, visit [virtual servers on GCP](https://cloud.google.com/intel). 

```

2024-11-04 19:30 UTC, mkbhanda commented on getting-started/README.md
> +We observe that the response is relavant and is based on the PDF uploaded.See the [ChatQnA Sample Guide](https://opea-project.github.io/latest/examples/ChatQnA/ChatQnA_Guide.html)
```suggestion
We observe that the response is relevant and is based on the PDF uploaded. See the [ChatQnA Sample Guide](https://opea-project.github.io/latest/examples/ChatQnA/ChatQnA_Guide.html)

```

2024-11-04 19:42 UTC, mkbhanda approved these changes
LGTM

2024-11-04 19:43 UTC, merged