Doc template
opea-project/docs pull request #76
Opened 2024-08-23 21:41 UTC by tomlenth

updated template per discussion with Preethi.  Add xeon deploy placeholder.

2024-08-24 11:56 UTC, dbkinder requested changes
Stray = in the top table line prevents the table from being recognized :(

2024-08-24 11:56 UTC, dbkinder commented on examples/ChatQnA/ChatQnA_Guide.rst
> ++--------------------------------------------=-----------------------------------------+
```suggestion
+--------------------------------------------------------------------------------------+
```

2024-08-24 11:56 UTC, dbkinder commented on examples/ChatQnA/ChatQnA_Guide.rst
> ++--------------------------------------------=-----------------------------------------+
```suggestion
+--------------------------------------------------------------------------------------+
```

2024-08-24 11:56 UTC, dbkinder commented on examples/ChatQnA/ChatQnA_Guide.rst
> ++--------------------------------------------=-----------------------------------------+
```suggestion
+--------------------------------------------------------------------------------------+
```

2024-08-29 00:21 UTC, dbkinder approved these changes

2024-08-29 00:25 UTC, hshen14 approved these changes

2024-08-29 00:25 UTC, merged