Add workflow executor agent strategy rfc
opea-project/docs pull request #77
Opened 2024-08-26 08:01 UTC by JoshuaL3000

2024-09-27 21:16 UTC, dbkinder requested changes

2024-09-27 21:16 UTC, dbkinder commented on community/rfcs/24-08-05-OPEA-Workflow-Executor Example.md
> +## Author
**Please rename the file with no spaces in the filename.**

Add a title as the first line
```
# 24-08-05 OPEA Workflow Executor Example
```

2024-09-30 13:41 UTC, dbkinder approved these changes
LGTM, thanks

2024-10-08 19:16 UTC, chickenrae approved these changes

2025-03-24 05:03 UTC, yinghu5 approved these changes
LGTM

2025-03-24 05:03 UTC, merged